# Generated by Django 4.2.11 on 2024-04-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_order', models.IntegerField()),
                ('full_name', models.TextField()),
                ('objects_of_examination', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('fo', models.CharField(max_length=255)),
                ('e_mail', models.EmailField(max_length=254)),
                ('order_date', models.DateTimeField()),
                ('order_number', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
